env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=240
jobs:
  tests:
    continue-on-error: ${{ matrix.ignore-if-missing }}
    permissions:
      actions: read
      checks: write
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Artifacts
      uses: dawidd6/action-download-artifact@v3.0.0
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: test-results-${{ matrix.setup }}
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: completed
    - continue-on-error: true
      name: Publish Test Report
      uses: scacap/action-surefire-report@v1.7.3
      with:
        check_name: ${{ matrix.setup }} test reports
        commit: ${{ github.event.workflow_run.head_commit.id }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: '**/target/surefire-reports/TEST-*.xml'
    strategy:
      fail-fast: false
      matrix:
        ignore-if-missing:
        - false
        include:
        - ignore-if-missing: true
          setup: linux-x86_64-java8
        - setup: linux-x86_64-java11
        - setup: linux-x86_64-java11-boringssl
        - setup: linux-x86_64-java17
        - setup: linux-x86_64-java18
        - setup: linux-x86_64-java21
        - setup: linux-x86_64-java22
        - setup: windows-x86_64-java11-boringssl
name: PR Reports
on:
  repository_dispatch:
    types: trigger-ga___ci-pr-reports.yml
permissions: read-all
